import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import data from '../data/education.json'
import { useState } from 'react'
import Card from '@/components/Card'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  console.log(data);
  const [information,setInformation ] =useState([...data])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Link href="about">About</Link>
        {
         
          // the first infomation is to check if there is information, if there is map()
          information && information.map((info, index) => {
            // info is the elment or object in the array education.json
            if (info.department.toLowerCase() === "business") {
              return (
                <Card key ={index} degree={info.degree} colour="red" font="10px" />
              )
              {/* <div key={index}>{info.degree}</div>
      if there is no key = {index} inside the div then
      compiler doesn't know at which point it should return the value */}
            }

            if (info.department.toLowerCase() === "computing") {
              return (
                
                <Card key ={index} degree={info.degree} colour="blue" font="50px" />
                // <div key={index}>{info.degree}</div>
              )
            }
          })
          
       }
      </main>
    </>
  )
}
