import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import data from '../data/education.json'
import { useState } from 'react'
import Card from '@/components/Card'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  console.log(data)
  const [information, setInformation] = useState([...data])


  return (
    <>

      <Head>
        <title>Student Bursary winners</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <nav className={styles.nav}>
          <ul className={styles.links}>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="about">About</Link>
            </li>
            <li>
              <Link href="contact">Contact</Link>
            </li>

          </ul>


        </nav>
        <h1 className={styles.title}>Student Winners</h1>
        <div className={styles.text_container}>
          <p className={styles.text}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus animi impedit suscipit architecto, odio inventore nostrum non neque dicta. Quam magni accusantium culpa distinctio tempore iure accusamus, dolorem nobis odit.</p>
          <p className={styles.text}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus animi impedit suscipit architecto, odio inventore nostrum non neque dicta. Quam magni accusantium culpa distinctio tempore iure accusamus, dolorem nobis odit.</p>
        </div>
        <button className={styles.btn}>Click to apply</button>

        <div className={styles.container}>
          {
            information && information.map((info, index) => {
              if (info.department.toLowerCase() === "business") {
                return (
                  <Card key={index} degree={info.degree} colour="DarkSalmon" />
                )
              }
            })

          }</div>

        <div className={styles.container}>
          {
            information && information.map((info, index) => {
              if (info.department.toLowerCase() === "computing") {
                return (
                  <Card key={index} degree={info.degree} colour="MediumSlateBlue" font="20px" />
                )
              }
            })
          }</div>
      </main>

      <footer className={styles.footer}>2023 Copy Right</footer>
    </>
  )
}
